filename: ../logs/log.log
# a:append,追加；w:write,覆盖
filemode: a
# "%(asctime)s - %(filename)s -%(name)s -%(levelname)s - %(message)s"
format  : "%(asctime)s - %(levelname)s - %(message)s"
# 日志必须是大写DEBUG,INFO,WARNING,ERROR
level   : INFO
